export const LOAD_ENTRIES_REQUEST = 'LOAD_ENTRIES_REQUEST';
export const LOAD_ENTRIES_SUCCESS = 'LOAD_ENTRIES_SUCCESS';
export const LOAD_ENTRIES_FAILURE = 'LOAD_ENTRIES_FAILURE';

export const ADD_ENTRY_REQUEST = 'ADD_ENTRY_REQUEST';
export const ADD_ENTRY_SUCCESS = 'ADD_ENTRY_SUCCESS';
export const ADD_ENTRY_FAILURE = 'ADD_ENTRY_FAILURE';

export const DELETE_ENTRY_REQUEST = 'DELETE_ENTRY_REQUEST';
export const DELETE_ENTRY_SUCCESS = 'DELETE_ENTRY_SUCCESS';
export const DELETE_ENTRY_FAILURE = 'DELETE_ENTRY_FAILURE';

export const EDIT_ENTRY_REQUEST = 'EDIT_ENTRY_REQUEST';
export const EDIT_ENTRY_SUCCESS = 'EDIT_ENTRY_SUCCESS';
export const EDIT_ENTRY_FAILURE = 'EDIT_ENTRY_FAILURE';

export const SET_USER_ID = 'SET_USER_ID';

export const VALUE_CLASSES = {
  20: 'very-low',
  40: 'low',
  60: 'mid',
  80: 'high',
  100: 'very-high'
};
